### ISSUE TITLE
Implementation of Browser Extension in React 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#10]
Integrate a browser API with the cloud-based MongoDB database to enable job review pop-ups and automatic form filling while browsing or applying for job postings.

**Comment by amaygada** [comment]
IMplemented a basic version of the extension that scrapes the title off campus enterprise websites.

**Comment by shaziamuckram** [comment]
Will look into this today!

**Comment by tahreemm** [comment]
Any updates on this @amaygada since we could not see the updated today

**Comment by amaygada** [comment]
Please check the correct branch. Focsuing on other pressing issues. Haven't moved past the basic extension.

**Comment by shaziamuckram** [comment]
Tested and looks all good!
