### ISSUE TITLE
Not able to run the application after the new merge from browser integration branch

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#12]
It says page not found error. There might be a problem with views.py.

**Comment by amaygada** [comment]
As per the discussion, the error was an illusion in the backend GUI. This is fixed now.

**Comment by shaziamuckram** [comment]
Yes, this is fixed and works well on my end. @tahreem are you good with this as well?

**Comment by tahreemm** [comment]
Yes it is also working at my end

**Comment by tahreemm** [comment]
Closing issue since it is working for all of us
