### ISSUE TITLE
AttributeError at /auth/token 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#14]
Client object has no attribute id with post request method

**Comment by shaziamuckram** [comment]
@amaygada any update on this fix?

**Comment by amaygada** [comment]
Fixed this. Was caused by django's jwt engine looking for id. I changed it such that it looks for the username as a unique field. Works now. Merged into my branch frontend/amay. Creaing a pull request. please accept it.

**Comment by tahreemm** [comment]
Changes are visible - closing the issue
