### ISSUE TITLE
DOI Badge and Coverage Badge 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#18]
Fixing the linking of these badges to external websites.

**Comment by shaziamuckram** [comment]
The DOI badge was attached successfully. We need to make sure that we do more releases as we go through the project. What we have now is a pre-release.

**Comment by shaziamuckram** [comment]
The coverage badge needs your permission @amaygada

**Comment by amaygada** [comment]
Let's look into that today.

**Comment by shaziamuckram** [comment]
Fixed and done!
