### ISSUE TITLE
Add JWT login to Django 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/CampusJobReview#8]
It focuses on enabling secure user login and token-based authentication for API endpoints.

**Comment by shaziamuckram** [comment]
This has been taken care of and tested. The associated files are under the auth_review folder. Check out the models.py, views.py, urls.py, and serializers.py. Please test this on your end and validate.

**Comment by tahreemm** [comment]
I can see the relevant brach being pulled - closing the issue
